title: reverse_with_unex()
description: | # this means to ignore newlines until "baseurl:"
  Let's figure out something with asking 'Why?'.
  I'm posting my personal researchs and projects about reverse engineering.
  Mainly focused on x86, also Windows PE's and several stuffs.
  Currently completing my education on Alaaddin Keykubat University Computer Engineering.
# Build settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one